server:
  port: 9005
spring:
  application:
    name: admin
      #rabbitmq:
      #host: 54.255.190.7
      #port: 5672
      #username: adminw
    #password: admin345
  redis:
    host: 127.0.0.1
    port: 6379
    password: admin123
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chuangyue_asset?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:com/cy/asset/**/mapper/*.xml # mapper文件扫描



