package com.cy.asset.task.bean;

/**
 * @author wc
 * @date 2020/12/2
 * @describe 美团个案信息
 */
public class MeiTuanCase extends CaseBean{

    /** 催收组 **/
    private String collection_phase;
    /** 跟进人 **/
    private String followUpPeople;
    /** 跟进人Code **/
    private String followUpPeopleCode;
    /** 分案日期 **/
    private String caseSerialNumber;
    /** 到期日 **/
    private String caseSerialNumber1;
    /** 特殊标识 **/
    private String caseSerialNumber2;
    /** 产品 **/
    private String caseSerialNumber3;
    /** 客户号 **/
    private String caseSerialNumber4;
    /** 客户姓名 **/
    private String caseSerialNumber5;
    /** 身份证号 **/
    private String caseSerialNumber6;
    /** 手机号 **/
    private String caseSerialNumber7;
    /** 联系人姓名 **/
    private String caseSerialNumber8;
    /** 联系人手机号 **/
    private String caseSerialNumber9;
    /** 应还日 **/
    private String caseSerialNumbe1r;
    /** 逾期借据借款金额 **/
    private String caseSerialNumbe2r;
    /** 逾期借据笔数 **/
    private String caseSerialNumbe3r;
    /** 逾期借据借款时间 **/
    private String caseSerialNumbe4r;
    /** 逾期阶段 **/
    private String caseSerialNumbe5r;
    /** 逾期天数 **/
    private String caseSerialNumbe6r;
    /** 逾期金额 **/
    private String caseSerialNumbe7r;
    /** 逾期本金 **/
    private String caseSerialNumbe8r;
    /** 逾期利息 **/
    private String caseSerialNumbe9r;
    /** 逾期罚息 **/
    private String caseSerialNumb1er;
    /** 逾期费用 **/
    private String caseSerialNumb2er;
    /** 提前结清金额 **/
    private String caseSerialNumb3er;
    /** 剩余本金 **/
    private String caseSerialNumb4er;
    /** 在催金额 **/
    private String caseSerialNumb5er;
    /** 低敏电话_未验证 **/
    private String caseSerialNumb6er;
    /** 中敏电话_未验证 **/
    private String caseSerialNumb7er;
    /** 高敏一级电话_未验证 **/
    private String caseSerialNumb8er;
    /** 低敏地址_未验证 **/
    private String caseSerialNumb9er;
    /** 中敏地址_未验证 **/
    private String caseSerialNum1ber;
    /** 高敏一级地址_未验证 **/
    private String caseSerialNum2ber;
    /** poi门店列表 **/
    private String caseSerialNum3ber;
    /** 高敏二级电话_未验证 **/
    private String caseSerialNum4ber;
    /** 高敏二级地址_未验证 **/
    private String caseSerialNum5ber;
    /** 协催授权 **/
    private String caseSerialNum6ber;
    /** 常驻省份 **/
    private String caseSerialNum7ber;
    /** 免息金额 **/
    private String caseSerialNum8ber;
    /** 伪冒标识 **/
    private String caseSerialNum9ber;
    /** 催收策略标签 **/
    private String caseSerialNum0ber;

}
